spring.docker.compose.enabled=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

management.endpoint.health.show-details=never

logging.level.com.taskmanager=INFO

app.cors.origins=${CORS_ORIGINS:http://localhost:4200}