spring.application.name=task-manager-api
spring.jpa.show-sql=true


spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never


logging.level.com.taskmanager=DEBUG

app.cors.origins=http://localhost:4200

spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=validate